version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "0.0.0.0:3306:3306"

  urlshortener:
    build: .
    restart: always
    network_mode: host
    ports:
      - "5000:5000"
    depends_on:
      - mariadb

